### ISSUE TITLE
Feature request: Apply replacement in selected region

### ISSUE THREAD

**Issue by TroySigX** [AckslD/muren.nvim#21]
How about only executing substitution in selected area in visual mode?

**Comment by AckslD** [comment]
That should already work if you call eg `MurenToggle` in visual mode. Is it not?

**Comment by TroySigX** [comment]
When I tried to do that, neovim shows the error `'<,'>MurenToggle E492: Not an editor command: '<,'>MurenToggle`

**Comment by AckslD** [comment]
Are you on the latest version or `muren`?

**Comment by TroySigX** [comment]
Yes, I updated it 3 hours ago

**Comment by TroySigX** [comment]
Hmm, now that I try it, it works, sorry about that
