### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by leandrochiarini** [AckslD/muren.nvim#27]
Hi there,

I have been trying to install the plugin with packer using a simple packer config:

```
return require('packer').startup(function(use)
-- Packer - plugin management {{{
use 'wbthomason/packer.nvim'
-- }}}
--

use 'AckslD/muren.nvim'

  -- Put this at the end after all plugins
  if PACKER_BOOTSTRAP then
    require('packer').sync()
  end
end)
```

Once I save, and install, by using `PackerStatus` I get:

>                 packer.nvim - Total plugins: 2
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> • muren.nvim
> • packer.nvim

And if I use `:h muren.nvim-muren.nvim`, I do get the right document. However, if I try to use `:MurenOpen`  or any other command, I get `E492: Not an editor command: MurenOpen`. 

My nvim version is:
>NVIM v0.9.0
>Build type: Release
>LuaJIT 2.1.0-beta3

I thought the problem was with packer, but I tested adding some other plugins and things were working just fine. I appreciate any help in advance.

**Comment by AckslD** [comment]
Try calling `require('muren').setup()`

**Comment by leandrochiarini** [comment]
Well, that was easy. Thank you!
