### ISSUE TITLE
[Question]: pattern to exclude files

### ISSUE THREAD

**Issue by dpetka2001** [AckslD/muren.nvim#28]
Is it possible to provide a pattern to files to exclude some possible filename patterns? What kind of regexes does `muren` support?

**Comment by AckslD** [comment]
You can use the `files` entry in the options panel. The pattern is passed to `:vimgrep`.

**Comment by dpetka2001** [comment]
So it's vim regex that the `files` entry supports? 

Edit: Oh it's a search pattern for vimgrep. I'm not familiar, so I will read some help files to get up to speed.

**Comment by AckslD** [comment]
It's passed as the second argument (`{file}`) to `:vimgrep`
