### ISSUE TITLE
Feature request: replace only in selected area

### ISSUE THREAD

**Issue by TroySigX** [AckslD/muren.nvim#30]

**Comment by AckslD** [comment]
Doesn't supplying a range to the command work? That's the intention at least

**Comment by TroySigX** [comment]
I believe I've supplied the range. Here's my config:
``` lua
local M = {}

function M.setup()
  require('muren').setup()
end

function M.keymaps()
  require('which-key').register({
    ['<C-s>'] = { function() require('muren.api').toggle_ui() end, 'Toggle [S]ubstitute' },
  }, { mode = { 'n', 'v' } })
end

return M
```
I chose a range and then press `<C-s>` to replace, but instead of just applying that specific range, it replaced the whole file

**Comment by TroySigX** [comment]
Oh, I see. Because instead of use the vim command, I used the api to toggle the UI, so I can't replace in range. Sorry for that.
