### ISSUE TITLE
Using this plugin breaks neovim's last substitution functionality (`:s//~/&` or `g&`)

### ISSUE THREAD

**Issue by kmoschcau** [AckslD/muren.nvim#36]
Hi, when I enable this plugin, the normal mode keymap `g&` or the substitution character `~` only replace an empty string, instead of the last substitution string.

**Comment by kmoschcau** [comment]
Actually false alarm, something else is going with my plugins I am guessing. There's a good chance it's not this one.

**Comment by kmoschcau** [comment]
OK I found the real culprit by doing a bisect search through my plugins. It's `trim.nvim`. https://github.com/cappyzawa/trim.nvim/issues/27

**Comment by AckslD** [comment]
Glad to hear you found it @kmoschcau
